using UnityEngine;

public class RecycleMarble : MonoBehaviour
{
    // ^Μu]计q
    public static int recycleMarbles;

    public GameManager gm;
    private void OnTriggerEnter(Collider other)
    {
        if (other.name.Contains("u]"))
        {
            other.gameObject.GetComponent<Rigidbody>().velocity = Vector3.zero;
            other.transform.position = new Vector3(100, 0, 0);


            // ^Μu]计qW[
            recycleMarbles++;
            // pG^Μ计q 单 ┮Τu]计q ち传 寄よ^X
            if (recycleMarbles != ControlSystem.shootMarbles) { return; }
            
            gm.SwitchTurn(false);

            if (gm.monsterParent.childCount == 0) { gm.SwitchTurn(true); }
        }
    }

}
